name: google_mlkit_commons
description: A Flutter plugin with commons files to implement google's standalone ml kit made for mobile platform.
version: 0.6.1
homepage: https://github.com/flutter-ml/google_ml_kit_flutter

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_commons
        pluginClass: GoogleMlKitCommonsPlugin
      ios:
        pluginClass: GoogleMlKitCommonsPlugin
