name: google_ml_kit
description: "A Flutter plugin to use all APIs from Google's standalone ML Kit for mobile platforms."
version: 0.20.0
homepage: https://github.com/flutter-ml/google_ml_kit_flutter
repository: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_ml_kit

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Vision APIs
  google_mlkit_commons: ^0.9.0
  google_mlkit_barcode_scanning: ^0.13.0
  google_mlkit_digital_ink_recognition: ^0.13.0
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_face_mesh_detection: ^0.3.0
  google_mlkit_image_labeling: ^0.13.0
  google_mlkit_object_detection: ^0.14.0
  google_mlkit_pose_detection: ^0.13.0
  google_mlkit_selfie_segmentation: ^0.9.0
  google_mlkit_text_recognition: ^0.14.0

  # Natural Language APIs
  google_mlkit_entity_extraction: ^0.14.0
  google_mlkit_language_id: ^0.12.0
  google_mlkit_translation: ^0.12.0
  google_mlkit_smart_reply: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
