name: google_ml_kit
description: A Flutter plugin to use all APIs from Google's standalone ML Kit for mobile platforms.
version: 0.14.0
homepage: https://github.com/flutter-ml/google_ml_kit_flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Vision APIs
  google_mlkit_barcode_scanning: ^0.6.0
  google_mlkit_digital_ink_recognition: ^0.7.0
  google_mlkit_face_detection: ^0.6.0
  google_mlkit_image_labeling: ^0.6.0
  google_mlkit_object_detection: ^0.7.0
  google_mlkit_pose_detection: ^0.6.0
  google_mlkit_selfie_segmentation: ^0.3.0
  google_mlkit_text_recognition: ^0.6.0

  # uncomment these lines when working on the local plugins
#  google_mlkit_commons:
#    path: ../google_mlkit_commons
#  google_mlkit_barcode_scanning:
#    path: ../google_mlkit_barcode_scanning
#  google_mlkit_digital_ink_recognition:
#    path: ../google_mlkit_digital_ink_recognition
#  google_mlkit_face_detection:
#    path: ../google_mlkit_face_detection
#  google_mlkit_image_labeling:
#    path: ../google_mlkit_image_labeling
#  google_mlkit_object_detection:
#    path: ../google_mlkit_object_detection
#  google_mlkit_pose_detection:
#    path: ../google_mlkit_pose_detection
#  google_mlkit_selfie_segmentation:
#    path: ../google_mlkit_selfie_segmentation
#  google_mlkit_text_recognition:
#    path: ../google_mlkit_text_recognition

  # Natural Language APIs
  google_mlkit_entity_extraction: ^0.7.0
  google_mlkit_language_id: ^0.6.0
  google_mlkit_translation: ^0.6.0
  google_mlkit_smart_reply: ^0.6.0

  # uncomment these lines when working on the local plugins
#  google_mlkit_entity_extraction:
#    path: ../google_mlkit_entity_extraction
#  google_mlkit_language_id:
#    path: ../google_mlkit_language_id
#  google_mlkit_translation:
#    path: ../google_mlkit_translation
#  google_mlkit_smart_reply:
#    path: ../google_mlkit_smart_reply

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
