name: google_mlkit_language_id
description: "A Flutter plugin to use Google's ML Kit Language Identification to determine the language of a string of text."
version: 0.13.0
homepage: https://github.com/flutter-ml/google_ml_kit_flutter
repository: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_language_id

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_language_id
        pluginClass: GoogleMlKitLanguageIdPlugin
      ios:
        pluginClass: GoogleMlKitLanguageIdPlugin
