name: google_mlkit_language_id
description: A Flutter plugin to use Google's ML Kit Language Identification to determine the language of a string of text.
version: 0.9.0
homepage: https://github.com/flutter-ml/google_ml_kit_flutter

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_language_id
        pluginClass: GoogleMlKitLanguageIdPlugin
      ios:
        pluginClass: GoogleMlKitLanguageIdPlugin
