name: google_mlkit_face_mesh_detection
description: A Flutter plugin to use Google's ML Kit Face Mesh Detection.
version: 0.0.2
homepage: https://github.com/flutter-ml/google_ml_kit_flutter

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.6.0
#    path: ../google_mlkit_commons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_face_mesh_detection
        pluginClass: GoogleMlKitFaceMeshDetectionPlugin
      ios:
        pluginClass: GoogleMlKitFaceMeshDetectionPlugin
