name: google_mlkit_pose_detection
description: A Flutter plugin to use Google's ML Kit Pose Detection to detect the pose of a subject's body in real time from a continuous video or static image.
version: 0.12.1
homepage: https://github.com/flutter-ml/google_ml_kit_flutter
repository: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_pose_detection

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_pose_detection
        pluginClass: GoogleMlKitPoseDetectionPlugin
      ios:
        pluginClass: GoogleMlKitPoseDetectionPlugin
