name: google_mlkit_smart_reply
description: A Flutter plugin to use Google's ML Kit Smart Reply API to automatically generate relevant replies to messages.
version: 0.12.0
homepage: https://github.com/flutter-ml/google_ml_kit_flutter
repository: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_smart_reply

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_smart_reply
        pluginClass: GoogleMlKitSmartReplyPlugin
      ios:
        pluginClass: GoogleMlKitSmartReplyPlugin
