name: google_mlkit_document_scanner
description: A Flutter plugin to use the ML Kit document scanner API to easily add a document scanner feature to your app.
version: 0.2.1
homepage: https://github.com/flutter-ml/google_ml_kit_flutter
repository: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_document_scanner

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_document_scanner
        pluginClass: GoogleMlKitDocumentScannerPlugin
      ios:
        pluginClass: GoogleMlKitDocumentScannerPlugin
